export const assets = {
  logo: 'branding/pathpilot-logo.png',
  music: 'audio/background-music.mp3',
  formToProcessingRecording: 'recordings/2026-07-17 22-45-14.mp4',
  generationAndRoadmapRecording: 'recordings/2026-07-17 22-46-12.mp4',
  replanningRecording: 'recordings/2026-07-17 22-50-03.mp4',
  exportRecording: 'recordings/2026-07-17 22-51-38.mp4',
  landing: 'screenshots/landing.png',
  createJourney: 'screenshots/create.png',
  generationFallback: 'screenshots/processing.png',
  roadmap: 'screenshots/roadmap.png',
  strategies: 'screenshots/alternative.png',
  explainWhy: 'screenshots/explainwhy.png',
  replanningFallback: 'screenshots/replanpanel.png',
  dashboard: 'screenshots/dashboard.png',
  resources: 'screenshots/resources.png',
  pdf: 'screenshots/pdf.png',
  share: 'screenshots/share.png',
  mobile: 'screenshots/mobile.png',
  ending: 'branding/pathpilot-ending.png',
} as const;
