export const assets = {
  logo: 'branding/pathpilot-logo.png',
  music: 'audio/background-music.mp3',
  hook: 'recordings/01-hook.mp4',
  landing: 'screenshots/landing.png',
  createJourney: 'screenshots/create.png',
  generation: 'recordings/03_processing.mp4',
  generationFallback: 'screenshots/processing.png',
  roadmap: 'screenshots/roadmap.png',
  strategies: 'screenshots/alternative.png',
  explainWhy: 'screenshots/explainwhy.png',
  replanning: 'recordings/08_replanning.mp4',
  replanningFallback: 'screenshots/replanpanel.png',
  dashboard: 'screenshots/dashboard.png',
  resources: 'screenshots/resources.png',
  pdf: 'screenshots/pdf.png',
  share: 'screenshots/share.png',
  mobile: 'screenshots/mobile.png',
  ending: 'branding/pathpilot-ending.png',
} as const;
